```js
const p1 = new Promise((resolve) => {
  setTimeout(() => {
    resolve("resolve3");
    console.log("timer1");
  }, 0);
  resolve("resovle1");
  resolve("resolve2");
})
  .then((res) => {
    console.log(res);
    setTimeout(() => {
      console.log(p1);
    }, 1000);
  })
  .finally((res) => { 
    console.log("finally", res); 
  });
```

我的错误答案

```js
  // finally resolve1
  // resolve1
  //timer1
  // finally resolve3
```

- 执行顺序的问题
  - 无论结果是fulfilled或者是rejected，在执行then()和catch()**后**，都会执行finally指定的回调函数,
  - 所以then先执行
- 由于无法知道promise的最终状态，所以finally的回调函数中不接收任何参数
  - 所以这里res一直都是undefined
- finally只执行一次
- then中的setTimeout被遗忘
- p1 = promise{ undefined }没懂

```js
//正确答案
//resovle1
finally undefined
timer1
Promise { undefined }
```



